AllCops:
  TargetRubyVersion: 2.2
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 200
Style/RedundantSelf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/Debugger:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/CaseEquality:
  Enabled: false

# Offense count: 13
Metrics/CyclomaticComplexity:
  Max: 28

# Offense count: 11
Metrics/PerceivedComplexity:
  Max: 23
